app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use Illuminate\Support\Facades\Route;


Route::get('_debugbar/assets/stylesheets', [
    'as' => 'debugbar-css',
    'uses' => '\Barryvdh\Debugbar\Controllers\AssetController@css'
]);

Route::get('_debugbar/assets/javascript', [
    'as' => 'debugbar-js',
    'uses' => '\Barryvdh\Debugbar\Controllers\AssetController@js'
]);

Route::get('_debugbar/open', [
    'as' => 'debugbar-open',
    'uses' => '\Barryvdh\Debugbar\Controllers\OpenController@handler'
]);


//diyetisyen panel
Route::get('/backoffice/login', 'Auth\AdminController@getLogin');
Route::post('/backoffice/login', 'Auth\AdminController@postLogin');
Route::get('/backoffice/logout', 'Auth\AdminController@getLogout');

//admin panel
Route::get('/admin/login', 'Auth\OfficeController@getLogin');
Route::post('/admin/login', 'Auth\OfficeController@postLogin');
Route::get('/admin/logout', 'Auth\OfficeController@getLogout');


Route::group(['prefix' => 'admin', 'middleware' => ['authOffice'], 'namespace' => 'Office'], function () {

    Route::controller('user', 'UserController',
        [
            'getIndex' => 'office.user.index',
            'getUpsert' => 'office.user.upsert',
            'postUpsert' => 'office.user.upsert',
            'getSpam' => 'office.user.spam',
            'getDiyetisyen' => 'office.user.diyetisyen',
            'getLogas' => 'office.user.logas'
        ]
    );

    Route::controller('nutrition', 'NutritionController',
        [
            'getIndex' => 'office.nutrition.index',
            'getUpsert' => 'office.nutrition.upsert',
            'postUpsert' => 'office.nutrition.upsert',
            'getChange' => 'office.nutrition.change',
            'getComments' => 'office.nutrition.comments',
            'postComments' => 'office.nutrition.comments'
        ]
    );

    Route::controller('portion', 'PortionController',
        [
            'getIndex' => 'office.portion.index',
            'postIndex' => 'office.portion.index',
            'getDetail' => 'office.portion.detail',
            'postDetail' => 'office.portion.detail'
        ]
    );

    Route::controller('notifications', 'NotificationsController',
        [
            'getIndex' => 'office.notifications.index',

        ]
    );

    Route::controller('blog', 'AboutController',
        [
            'getBlog' => 'office.pages.blog',
            'postBlog' => 'office.pages.blog'

        ]
    );

    Route::controller('terms', 'TermsController',
        [
            'getTerms' => 'office.pages.terms',
            'postTerms' => 'office.pages.terms'

        ]
    );
    Route::controller('privacy', 'PrivacyController',
        [
            'getPrivacy' => 'office.pages.privacy',
            'postPrivacy' => 'office.pages.privacy'

        ]
    );

    Route::controller('about', 'AboutController',
        [
            'getAbout' => 'office.pages.about',
            'postAbout' => 'office.pages.about'

        ]
    );

    Route::controller('list', 'DietListController',
        [
            'getIndex' => 'office.nutrition.dietlist'
        ]
    );

    Route::controller('coop', 'CoopController',
        [
            'getIndex' => 'office.coop.index',
            'getUpsert' => 'office.coop.upsert',
            'postUpsert' => 'office.coop.upsert'
        ]
    );

    Route::controller('export', 'ExcelController',
        [
            'getIndex' => 'office.excel.index'
        ]
    );


    Route::controller('/', 'HomeController', ['getIndex' => 'office.dash']);

});

Route::group(['prefix' => 'backoffice', 'middleware' => ['authAdmin'], 'namespace' => 'Panel'], function () {

    Route::controller('user', 'UserController',
        [
            'getIndex' => 'admin.user.index',
            'getUpsert' => 'admin.user.upsert',
            'postUpsert' => 'admin.user.upsert'
        ]
    );

    Route::controller('meal', 'MealController',
        [
            'getIndex' => 'admin.meals.index',
            'getPremium' => 'admin.meals.premium',
            'getUpsert' => 'admin.meals.upsert',
            'getChat' => 'admin.meals.chat',
            'getCloseChat' => 'admin.meals.closeChat'
        ]
    );

    Route::controller('userinfo', 'InfoController',
        [
            'getIndex' => 'admin.userinfo.index',
            'getUpsert' => 'admin.userinfo.upsert'
        ]
    );

    Route::controller('codes', 'CodesController',
        [
            'getIndex' => 'admin.codes.index',
            'postIndex' => 'admin.codes.index'
        ]
    );

    Route::controller('dietlist', 'DietlistController',
        [
            'getIndex' => 'admin.list.index',
            'getUpsert' => 'admin.list.upsert',
            'postUpsert' => 'admin.list.upsert'
        ]
    );

    Route::controller('detail', 'DetailController',
        [
            'getIndex' => 'admin.detail.index',
            /*'postIndex' => 'admin.detail.index'*/
        ]
    );


    Route::controller('/', 'HomeController', ['getIndex' => 'admin.dash']);

});

if (App::environment() == 'local') {
    $domain = ['namespace' => 'Api', 'prefix' => 'api'];
} elseif (App::environment() == 'prod') {
    $domain = ['namespace' => 'Api', 'domain' => 'apiv2.ceptediyetisyen.com'];
}


Route::group($domain, function () {

    Route::controller('device', 'DeviceController');
    Route::get('terms', 'HomeController@getTerms');
    Route::get('about', 'HomeController@getAbout');
    Route::get('privacy', 'HomeController@getPrivacy');
    Route::get('blog', 'HomeController@getBlog');


    Route::group(['middleware' => ['requestValidation', 'token']], function () {

        Route::controller('meal', 'MealController');
        Route::controller('user', 'UserController');
        Route::controller('toplist', 'ToplistController');
        Route::controller('notifications', 'NotificationController');
        Route::controller('comments', 'CommentController');
        Route::controller('payment', 'PaymentController');
        Route::controller('likes', 'LikeController');
        Route::controller('favorites', 'FavoriteController');
        Route::controller('dietlist', 'DietlistController');
        Route::controller('/', 'HomeController');
    });


});


Route::get('/', function () {

});

app/Models/Nutrition.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Nutrition extends Model
{
    public $table = 'users';
    protected $hidden = ['password', 'remember_token'];


    public function getPicAttribute($value)
    {
        if($value === ''){
            return asset('uploads/default.jpg');
        }
        return asset('uploads/'.$value);
    }

    public function newQuery($excludeDeleted = true)
    {
        $query = parent::newQuery($excludeDeleted);
        $query->where('status',1);
        return $query;
    }
}

resources/views/admin/dash/index.blade.php
@extends('admin.layouts.master')
@section('content')
    <div class="row">
        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="dashboard-stat2" style="height: 80px">
                <div class="display">
                    <div class="number">
                        <h3 class="font-green-sharp">
                            <span data-counter="counterup" data-value="{{$user_count}}">0</span>
                            <small class="font-green-sharp"></small>
                        </h3>
                        <small>HASTA</small>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="dashboard-stat2" style="height: 80px">
                <div class="display">
                    <div class="number">
                        <h3 class="font-green-sharp">
                            <span data-counter="counterup"
                                  data-value="@if(is_int($premium)) {{$premium}} @else 0 @endif">0</span>
                            <small class="font-green-sharp"></small>
                        </h3>
                        <small>PREMIUM HASTA</small>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="dashboard-stat2" style="height: 80px">
                <div class="display">
                    <div class="number">
                        <h3 class="font-green-sharp">
                            <span data-counter="counterup" data-value="{{$codes}}">0</span>
                            <small class="font-green-sharp"></small>
                        </h3>
                        <small>ÖZEL HASTA</small>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="dashboard-stat2" style="height: 80px">
                <div class="display">
                    <div class="number">
                        <h3 class="font-green-sharp">
                            <span data-counter="counterup"
                                  data-value="@if(is_int($diet_list)){{$diet_list}} @else 0 @endif">0</span>
                            <small class="font-green-sharp"></small>
                        </h3>
                        <small>DİYET LİSTESİ</small>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="dashboard-stat2" style="height: 80px">
                <div class="display">
                    <div class="number">
                        <h3 class="font-green-sharp">
                            <span data-counter="counterup" data-value="{{$comments}}">0</span>
                            <small class="font-green-sharp"></small>
                        </h3>
                        <small>YORUMSUZ</small>
                    </div>

                </div>
            </div>
        </div>

        <div class="col-lg-2 col-md-2 col-sm-6 col-xs-12">
            <div class="dashboard-stat2" style="height: 80px;">
                <div class="display">
                    <div class="number">
                        <h3 class="font-green-sharp">
                            <span data-counter="counterup" data-value="{{$diet}}">0</span>
                            <small class="font-green-sharp"></small>
                        </h3>
                        <small>LİSTE BEKLEYEN</small>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label" for="single">Yorumlanan Öğünler</label>
                <canvas id="myChart" width="997px" height="200px">
                    @foreach($commentByM as $i)
                        <div class="logs">{!! $i !!}</div>
                    @endforeach
                </canvas>
            </div>
        </div>
    </div>




    <div class="row">
        <div class="col-md-5">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <span class="caption-subject font-green-sharp bold uppercase">
                            Cevap Bekleyen 10 öğün
                        </span>
                    </div>
                </div>
                <div class="portlet-body">
                    <ul class="list-group">
                        @foreach($commentsByR as $meal)
                            <li class="list-group-item">
                                <a href="{{route('admin.meals.chat')}}/{{$meal->id}}">
                                    <img src="{{$meal->pic}}" width="50"/>
                                    <small>
                                        #{{$meal->user->id}}</small> {{$meal->user->first_name}} {{$meal->user->last_name}}  {{$meal->description}}
                                </a>
                            </li>
                        @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>



@endsection


@section('script')
    <script src="{{asset('assets/admin/global/scripts/Chart.min.js')}}" type="text/javascript"></script>
    <script>
        var ctx = document.getElementById("myChart");
        var DATA = [];
        function deneme() {
            var elems = document.getElementsByClassName("logs");
            for (elem of elems) {
                DATA.push(elem.innerHTML);
            }
            console.log(DATA);
        }
        deneme();

        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: DATA,
                datasets: [{
                    label: 'Yorumlanan Öğün Sayısı',
                    data: DATA,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
        });
    </script>


@endsection